### ISSUE TITLE
License

### ISSUE THREAD

**Issue by jpettitt** [jasonhinkle/php-gpg#25] opened 2016-01-04 06:52 UTC
You are only bound to GPL if you used their code.  The protocol is not copyrighted.

**Comment by DanielRuf** [comment] 2016-01-04 08:09
You are right. This was already mentioned in #22. As @certly is currently working on a fork, there is no mention of this anymore. Closing this as duplicate of #22

**Closed by DanielRuf** 2016-01-04 08:09 UTC
