### ISSUE TITLE
Decrypt big files

### ISSUE THREAD

**Issue by frederichoule** [jasonhinkle/php-gpg#5] opened 2014-07-18 16:04 UTC
Hey! When I try to decrypt bigger files (all the ones I have problem with are > 250kb), I get this error:

gpg: [don't know]: invalid packet (ctb=47)
gpg: WARNING: message was not integrity protected
gpg: [don't know]: invalid packet (ctb=31)
gpg: no valid OpenPGP data found.

I have a lot of files I encrypted that way, I had tested at first but with smaller files (80kb) and it worked great, so I didn't bother check with bigger files. Do you know what's going on?

Files are jpg/png files, base64ed first and then encrypted with your function.

**Comment by DanielRuf** [comment] 2015-10-23 13:40
duplicate of #1

**Closed** 2015-10-27 23:05 UTC
Labels: duplicate
